### ISSUE TITLE
These SVG images are so cute, how did you draw them?

### ISSUE THREAD

**Issue by jiangbo** [orhun/personal-blog#18]
Hi, Orhun
  In https://github.com/orhun/personal-blog/tree/main/content, zigxxxxx.svg are so cute, how did you draw them?

**Comment by orhun** [comment]
Hey,

They belong to the Zig project: https://github.com/ziglang/logo

I took the images from Zig release notes page: https://ziglang.org/download/0.10.1/release-notes.html

I should probably credit them somewhere 😅 any ideas?

**Comment by jiangbo** [comment]
I see these images for the first time, thank you.
